language: python
# Python releases to test
python:
  - 2.6
  - 2.7
  - 3.2
# Django releases
env:
  - DJANGO_VERSION=Django==1.4.10
  - DJANGO_VERSION=Django==1.5.5
  - DJANGO_VERSION=Django==1.6.1
# Exclude some Django releases depending on Python version
matrix:
  exclude:
    - python: 3.2
      env: DJANGO_VERSION=Django==1.4.10
install:
  - if [[ $TRAVIS_PYTHON_VERSION < '2.7' ]]; then pip install -q --use-mirrors argparse; fi
  - pip install -q --use-mirrors $DJANGO_VERSION
  - python setup.py install -q
script: make test
notifications:
  email:
    on_success: never
    on_failure: change
